/*******************************************************************************
 * Copyright (c) 2019, 2019 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

#ifndef OMR_COMPILER_OPTIONS_HPP
#define OMR_COMPILER_OPTIONS_HPP

#ifndef OMR_COMPILER_OPTIONS_CONNECTOR
#define OMR_COMPILER_OPTIONS_CONNECTOR
namespace OMR { class CompilerOptions; }
namespace OMR { typedef OMR::CompilerOptions CompilerOptionsConnector;}
#endif

#include "env/TRMemory.hpp"
#include "infra/Annotations.hpp"

namespace OMR
{


class OMR_EXTENSIBLE CompilerOptions
   {

public:

    TR_ALLOC(TR_Memory::CompilerOptions)


bool TR_TestOption1 = false;
bool TR_AOTCompileOnlyFromBootstrap = false;
bool TR_AOT                        = false;
bool TR_ReportMethodEnter          = false;
bool TR_ReportMethodExit           = false;
bool TR_EntryBreakPoints           = false;
bool TR_TestOption2 = false;
bool TR_StrictFP                   = false;
bool TR_StrictFPCompares           = false;
bool TR_RegisterMaps               = false;
bool TR_CreatePCMaps               = false;
bool TR_OptimizeForSpace           = false;
bool TR_MimicInterpreterFrameShape = false;
bool TR_TraceBC                    = false;
bool TR_TestOption3 = false;
bool TR_TraceInfo                  = false;
bool TR_TraceTrees                 = false;
bool TR_TraceCG                    = false;
bool TR_TraceAliases               = false;
bool TR_TraceOptTrees              = false;
bool TR_TraceOptDetails            = false;
bool TR_TraceAll                   = false;
bool TR_CountOptTransformations    = false;
bool TR_NoRecompile                = false;
bool TR_DebugBeforeCompile         = false;
bool TR_DebugOnEntry               = false;
bool TR_BreakBeforeCompile         = false;
bool TR_FailRecompile              = false;
bool TR_FailPreXRecompile          = false;
bool TR_TraceBBVA                  = false;
bool TR_TraceBVA                   = false;
bool TR_DisableInterpreterSampling = false;
bool TR_DisableEDO                 = false;
bool TR_DisableThrowToGoto         = false;
bool TR_DisableMonitorCoarsening   = false;
bool TR_DisableMergeNew            = false;
bool TR_DisableVirtualInlining     = false;
bool TR_DisableNonvirtualInlining  = false;
bool TR_DisableSyncMethodInlining  = false;
bool TR_DisableTailRecursion       = false;
bool TR_DisableInterfaceInlining   = false;
bool TR_DisableProfiledInlining    = false;
bool TR_DisableAbstractInlining    = false;
bool TR_DisableHierarchyInlining   = false;
bool TR_DisableDirectMemoryOps     = false;
bool TR_DisableArraySetOpts        = false;
bool TR_TraceLiveMonitorMetadata   = false;
bool TR_DisableAllocationInlining  = false;
bool TR_DisableInlineCheckCast     = false;
bool TR_DisableInlineIfInstanceOf  = false;
bool TR_DisableInlineInstanceOf    = false;
bool TR_TestOption4 = false;
bool TR_DisableInlineMonEnt        = false;
bool TR_DisableInlineMonExit       = false;
bool TR_DisableUnsafe              = false;
bool TR_DisableVirtualGuardNOPing  = false;
bool TR_DisableNewInstanceImplOpt  = false;
bool TR_DisableFastStringIndexOf   = false;
bool TR_DisableIPA                          = false; 
bool TR_DisableValueProfiling               = false; 
bool TR_DisableUpdateAOTBytesSize           = false; 
bool TR_DisableMergeStackMaps               = false; 
bool TR_DisableUpdateJITBytesSize           = false; 
bool TR_EnableParanoidOptCheck              = false; 
bool TR_AlwaysSafeFatal                     = false; 
bool TR_DisableReadMonitors                 = false; 
bool TR_DisableZ10                          = false; 
bool TR_TraceUseDefs                        = false; 
bool TR_TraceValueNumbers                   = false; 
bool TR_TraceLiveness                       = false; 
bool TR_BreakAfterCompile                   = false; 
bool TR_PrintErrorInfoOnCompFailure         = false; 
bool TR_DisableArrayCopyOpts                = false; 
bool TR_NoResumableTrapHandler              = false; 
bool TR_disableInterfaceCallCaching         = false;
bool TR_enableInterfaceCallCachingSingleDynamicSlot
                                                = false;
bool TR_DisableJava8StartupHeuristics       = false;
bool TR_DisableInlinerArgsPropagation       = false;
bool TR_DisableZ13                          = false;
bool TR_noJitDuringBootstrap                = false;
bool TR_DisableOnDemandLiteralPoolRegister  = false;
bool TR_DisableInternalPointers             = false;
bool TR_EnableNodeGC                        = false;
bool TR_OmitFramePointer                    = false;
bool TR_ForceAOT                            = false;
bool TR_noJitUntilMain                      = false;
bool TR_DisableMarkingOfHotFields           = false;
bool TR_DisableProfiling                    = false;
bool TR_Timing                              = false;
bool TR_SupportSwitchToInterpreter          = false;
bool TR_DisableFPCodeGen                    = false;
bool TR_Profile                             = false;
bool TR_DisableAsyncCompilation             = false;
bool TR_DisableCompilationThread            = false;
bool TR_EnableCompilationThread             = false;
bool TR_EnableJITaaSHeuristics              = false;
bool TR_SoftFailOnAssume                    = false;
bool TR_DisableNewBlockOrdering             = false;
bool TR_DisableZNext                        = false;
bool TR_DisableDynamicLoopTransfer          = false;
bool TR_TraceNodeFlags                      = false;
bool TR_DisableNewBVA                       = false;
bool TR_MaskAddresses                       = false;
bool TR_BreakBBStart                        = false; 
bool TR_DisableRXusage                      = false; 
bool TR_EnableInliningOfUnsafeForArraylets  = false; 
bool TR_DisableStringPeepholes              = false; 
bool TR_DisableCheapWarmOpts                = false; 
bool TR_DisableInliningDuringVPAtWarm       = false; 
bool TR_AlwaysFatalAssert                   = false; 
bool TR_DisableDynamicSamplingWindow        = false; 
bool TR_DisableAsyncCheckVersioning         = false; 
bool TR_DisableInterpreterProfiling         = false; 
bool TR_ConcurrentLPQ                       = false; 
bool TR_EnableVPICForResolvedVirtualCalls   = false; 
bool TR_DisableRegisterPressureSimulation   = false; 
bool TR_DisableBlockVersioner               = false; 
bool TR_TraceMarkingOfHotFields             = false; 
bool TR_EnableAnnotations                   = false;  // change to disable when on by default
bool TR_UnresolvedAreNotColdAtCold          = false;  // cold block marker marks unresolved blocks as cold at hotness cold or less
bool TR_UseSymbolValidationManager          = false; 
bool TR_EnablePIDExtension                  = false; 
bool TR_GenerateCompleteInlineRanges        = false; 
bool TR_DisableInliningOfNatives            = false; 
bool TR_AssignEveryGlobalRegister           = false; 
bool TR_DisableZ196                         = false; 
bool TR_EarlyLPQ                            = false; 
bool TR_DisableUpgradingColdCompilations    = false;  // for cold methods due to classLoadPhase for instance
bool TR_VerboseInterpreterProfiling         = false; 
bool TR_TraceRegisterPressureDetails        = false; 
bool TR_EnableYieldVMAccess                 = false; 
bool TR_DisableNoVMAccess                   = false; 
bool TR_DisableStoreSinking                 = false; 
bool TR_EnableJVMPILineNumbers              = false; 
bool TR_HWProfileDeleteEmptyBlocks          = false; 
bool TR_DisableLiveMonitorMetadata          = false; 
bool TR_DisableMonitorOpts                  = false; 
bool TR_ExperimentalClassLoadPhase          = false; 
bool TR_DisableLookahead                    = false; 
bool TR_TraceBFGeneration                   = false; 
bool TR_DisableDFP                          = false; 
bool TR_SuspendEarly                        = false; 
bool TR_EnableEarlyCompilationDuringIdleCpu = false; 
bool TR_DisableCallGraphInlining            = false;  // interpreter profiling
bool TR_enableProfiledDevirtualization      = false; 
bool TR_EnableValueTracing                  = false;  // run-time value tracing
bool TR_IgnoreAssert                        = false;  // ignore failing assertions
bool TR_EnableSymbolValidationManager       = false; 
bool TR_EnableNewAllocationProfiling        = false;  // enable tracing of fields load and store
bool TR_IgnoreIEEERestrictions              = false;  // enable more aggressive, nonIEEE compliant xforms
bool TR_ProcessHugeMethods                  = false;  // allow processing of huge methods
bool TR_FullSpeedDebug                      = false; 
bool TR_DynamicThreadPriority               = false; 
bool TR_UseIdleTime                         = false; 
bool TR_UseOptLevelAdjustment               = false; 
bool TR_DisableTraceRegDeps                 = false; 
bool TR_EnableCodeCacheConsolidation        = false; 
bool TR_DontJitIfSlotsSharedByRefAndNonRef  = false; 
bool TR_DisableAOTWarmRunThroughputImprovement  = false; 
bool TR_EnableUpgradingAllColdCompilations  = false; 
bool TR_TraceLastOpt                        = false; 
bool TR_UseILValidator                      = false; 
bool TR_DisableFPE                          = false; 
bool TR_EnableAggressiveLoopVersioning      = false; 
bool TR_EnableElementPrivatization          = false; 
bool TR_CompileBit                          = false; 
bool TR_WaitBit                             = false; 
bool TR_DisableZ14                          = false; 
bool TR_DisableLoopTransfer                 = false;  // disables the loop transfer part of loop versioner
bool TR_EnableRangeSplittingGRA             = false; 
bool TR_ForceUsePreexistence                = false; 
bool TR_TLHPrefetch                         = false; 
bool TR_ReservingLocks                      = false;  // Can be merged withbool TR_DisableLockResevation when lock reservation is enabled on all platforms
bool TR_DisableLockResevation               = false; 
bool TR_DisableNopBreakpointGuard           = false; 
bool TR_DisableAggressiveRecompilations     = false; 
bool TR_DisableVariablePrecisionDAA         = false; 
bool TR_ContinueAfterILValidationError      = false; 
bool TR_DisableScorchingSampleThresholdScalingBasedOnNumProc = false; 
bool TR_CummTiming                          = false; 
bool TR_ReserveAllLocks                     = false; 
bool TR_DisableSamplingJProfiling           = false; 
bool TR_UseSamplingJProfilingForLPQ         = false; 
bool TR_UseSamplingJProfilingForAllFirstTimeComps   = false; 
bool TR_NoStoreAOT                          = false; 
bool TR_NoLoadAOT                           = false; 
bool TR_DisableNewLoopTransfer              = false;  // loop versioning for virtual guards
bool TR_UseSamplingJProfilingForDLT                 = false; 
bool TR_UseSamplingJProfilingForInterpSampledMethods= false; 
bool TR_EmitRelocatableELFFile              = false; 
bool TR_DisableCodeCacheSnippets            = false; 
bool TR_EnableReassociation                 = false; 
bool TR_DisableSSOpts                       = false; 
bool TR_EnableFieldWatch                    = false; 
bool TR_DisableDelayRelocationForAOTCompilations   = false; 
bool TR_DisableRecompDueToInlinedMethodRedefinition = false; 
bool TR_DisableLoopReplicatorColdSideEntryCheck = false; 
bool TR_TraceVFPSubstitution                = false; 
bool TR_DontDowgradeToColdDuringGracePeriod = false; 
bool TR_EnableRecompilationPushing          = false; 
bool TR_EnableJCLInline                     = false;  // enable JCL Integer and Long methods inline
bool TR_DisableTreePatternMatching          = false; 
bool TR_TraceTreePatternMatching            = false; 
bool TR_DisableCHOpts                       = false; 
bool TR_ForceLoadAOT                        = false; 
bool TR_TraceRelocatableDataCG              = false; 
bool TR_TraceRelocatableDataRT              = false; 
bool TR_TraceRelocatableDataDetailsCG       = false; 
bool TR_TraceRelocatableDataDetailsRT       = false; 
bool TR_TurnOffSelectiveNoOptServerIfNoStartupHint = false; 
bool TR_TraceDominators                     = false; 
bool TR_EnableHCR                           = false;  // enable hot code replacement
bool TR_DisableTOCForConsts                 = false; 
bool TR_UseLowPriorityQueueDuringCLP        = false; 
bool TR_DisableVectorBCD                    = false; 
bool TR_EnableTrivialStoreSinking           = false; 
bool TR_DisableTraps                        = false; 
bool TR_EnableLowerCompilationLimitsDecisionMaking
                                          = false; 
bool TR_DisableDirectToJNI                  = false; 
bool TR_OldJVMPI                            = false; 
bool TR_EmitExecutableELFFile               = false; 
bool TR_DisableLinkageRegisterAllocation    = false; 
bool TR_DisableCompilationAfterDLT          = false; 
bool TR_DLTMostOnce                         = false; 
bool TR_DisableSelectiveNoOptServer         = false; 
bool TR_DisableStripMining                  = false; 
bool TR_EnableSharedCacheTiming             = false; 
bool TR_NoOptServer                         = false; 
bool TR_DisableDLTrecompilationPrevention   = false; 
bool TR_DisablePeekAOTResolutions           = false; 
bool TR_DisableLiveRangeSplitter            = false; 
bool TR_DisableHalfSlotSpills               = false; 
bool TR_DisableHysteresis                   = false;  // DFP
bool TR_DisableTLHPrefetch                  = false; 
bool TR_DisableJProfilerThread              = false; 
bool TR_DisableIProfilerThread              = false; 
bool TR_DisableGuardedCountingRecompilations = false; 
bool TR_EnableCompYieldStats                = false; 
bool TR_DisableBDLLVersioning               = false; 
bool TR_IProfilerPerformTimestampCheck      = false; 
bool TR_VerboseInlineProfiling              = false; 
bool TR_DisableIntegerCompareSimplification = false; 
bool TR_DisableAutoSIMD                      = false; 
bool TR_DisableOOL                          = false; 
bool TR_DisableWriteBarriersRangeCheck      = false; 
bool TR_Randomize                           = false; 
bool TR_BreakOnWriteBarrier                 = false; 
bool BreakOnWriteBarrierSnippet             = false; 
bool TR_Enable64BitRegsOn32Bit              = false; 
bool TR_CountWriteBarriersRT                = false; 
bool TR_DisableNoServerDuringStartup        = false;   // setbool TR_NoOptServer during startup and insert GCR trees
bool TR_BreakOnNew                          = false; 
bool TR_SinkAllStores                       = false; 
bool TR_SinkAllBlockedStores                = false; 
bool TR_DisableStoreAnchoring               = false; 
bool TR_FirstLevelProfiling                 = false; 
bool TR_DisableNewMethodOverride            = false; 
bool TR_EnableSequentialLoadStoreWarm       = false; 
bool TR_EnableSequentialLoadStoreCold       = false; 
bool TR_Enable64BitRegsOn32BitHeuristic     = false; 
bool TR_EnableNewX86PrefetchTLH             = false; 
bool TR_ConservativeCompilation             = false; 
bool TR_EnableLargeCodePages                = false; 
bool TR_EnableLargePages                    = false; 
bool TR_DisableNewX86VolatileSupport        = false; 
bool TR_Disable64BitRegsOn32Bit             = false; 
bool TR_Disable64BitRegsOn32BitHeuristic    = false; 
bool TR_TraceRegisterState                  = false; 
bool TR_DisableDirectToJNIInline            = false; 
bool TR_EnableSelectiveEnterExitHooks           = false; 
bool TR_OrderCompiles                           = false; 
bool TR_VerboseOptTransformations               = false; 
bool TR_DisableEnhancedClobberEval              = false; 
bool TR_Enable39064Epilogue                     = false; 
bool TR_FSDGRA                                  = false; 
bool TR_EnableLastCompilationRetrialLogging     = false; 
bool TR_EnableFastHotRecompilation              = false;  // RAS
bool TR_EnableFastScorchingRecompilation        = false;  // RAS
bool TR_DisableTarokInlineArrayletAllocation    = false;  // TAROK
bool TR_TraceAddAndRemoveEdge                   = false; 
bool TR_DisableHighWordRA                       = false;  // zGryphon
bool TR_DisableZImplicitNullChecks              = false; 
bool TR_DisablePrexistenceDuringGracePeriod     = false; 
bool TR_DisableInlineWriteBarriersRT            = false;  // RTJ
bool TR_DisableNewInliningInfrastructure        = false; 
bool TR_DisableZ13LoadAndMask                   = false; 
bool TR_DisablePartialInlining                  = false; 
bool TR_AssumeStartupPhaseUntilToldNotTo        = false; 
bool TR_X86UseMFENCE                            = false; 
bool TR_DisableHPRSpill                         = false;  // zGryphon
bool TR_DisableHPRUpgrade                       = false;  // zGryphon
bool TR_AggressiveOpts                          = false; 
bool TR_DisableMarshallingIntrinsics            = false; 
bool TR_DisablePackedDecimalIntrinsics          = false; 
bool TR_DisableDememoization                    = false; 
bool TR_DisableStringBuilderTransformer         = false; 
bool TR_TraceILGen                              = false; 
bool TR_DisableSharedCacheHints                 = false; 
bool TR_DisableAOTInstanceFieldResolution       = false; 
bool TR_DisableRefArraycopyRT                   = false; 
bool TR_StaticDebugCountersRequested            = false; 
bool TR_TraceNonLinearRegisterAssigner          = false; 
bool TR_TraceLookahead                          = false; 
bool TR_DisableMultiLeafArrayCopy               = false; 
bool TR_DisableInlinerFanIn                     = false; 
bool TR_EnableMonitorCacheLookup                = false; 
bool TR_TraceReloCG                             = false; 
bool TR_TraceTrivialDeadTreeRemoval             = false; 
bool TR_PaintAllocatedFrameSlotsDead            = false;  //x86 Only
bool TR_PaintAllocatedFrameSlotsFauxObject      = false;  //x86 Only
bool TR_RTGCMapCheck                            = false;  //x86 Only
bool TR_ImmediateCountingRecompilation          = false; 
bool TR_DisableDumpFlowGraph                    = false; 
bool TR_EnableEBBCCInfo                         = false; 
bool TR_DisableAOTColdCheapTacticalGRA                  = false; 
bool TR_EnableColdCheapTacticalGRA                      = false; 
bool TR_EnableDupRetTree                                = false; 
bool TR_DisableAOTStaticField                           = false; 
bool TR_DisableFreeCodeCacheBlockRecycling              = false; 
bool TR_ForceBCDInit                                    = false; 
bool TR_EnableAOTInlineSystemMethod                     = false; 
bool TR_EnableAOTMethodEnter                            = false; 
bool TR_DisableMaskVFTPointers                          = false; 
bool TR_NoAotSecondRunDetection                         = false; 
bool TR_DebugInliner                                    = false; 
bool TR_TracePartialInlining                            = false; 
bool TR_TraceOSR                                        = false; 
bool TR_EnableOSR                                       = false; 
bool TR_DisableAOTCheckCastInlining                     = false; 
bool TR_DisableAOTInstanceOfInlining                    = false; 
bool TR_EnableCFGEdgeCounters                           = false; 
bool TR_DisableIntrinsics                               = false; 
bool TR_DisablePersistIProfile                          = false; 
bool TR_DisableZArraySetUnroll                          = false; 
bool TR_NoIProfilerDuringStartupPhase                   = false; 
bool TR_ScalarizeSSOps                                  = false; 
bool TR_DisableIProfilerDataCollection                  = false; 
bool TR_CheckGRA                                        = false; 
bool TR_PoisonDeadSlots                                 = false; 
bool TR_DisableOSRSharedSlots                           = false; 
bool TR_DisableIncrementalCCR                           = false;  //SRT
bool TR_DisableOSRCallSiteRemat                         = false; 
bool TR_UseLowerMethodCounts                            = false; 
bool TR_DisableOSRLocalRemat                            = false; 
bool TR_DoNotUsePersistentIprofiler                     = false; 
bool TR_DoNotUseFastStackwalk                           = false; 
bool TR_DisableOSRLiveRangeAnalysis                     = false; 
bool TR_DisableDowngradeToColdOnVMPhaseStartup          = false; 
bool TR_DontDowngradeToCold                             = false; 
bool TR_VerbosePseudoRandom                             = false; 
bool TR_DisableDoubleWordStackAlignment                 = false;  //390
bool TR_ForceNonSMP                                     = false; 
bool TR_jitAllAtMain                                    = false; 
bool TR_EnableAOTMethodExit                             = false; 
bool TR_DisableEmptyPreHeaderCheck                      = false; 
bool TR_SinkOnlyCCStores                                = false; 
bool TR_EnableDeterministicOrientedCompilation          = false; 
bool TR_EnableAOTStats                                  = false; 
bool TR_DisableSynchronizedFieldLoad                    = false; 
bool TR_QuickProfile                                    = false; 
bool TR_DisableVerification                             = false; 
bool TR_DisableZEC12                                    = false; 
bool TR_BreakOnJ2IThunk                                 = false; 
bool TR_DisableGlobalStaticBaseRegister                 = false; 
bool TR_DisableMethodHandleThunks                       = false; 
bool TR_KeepBCDWidening                                 = false; 
bool TR_CodeCacheSanityCheck                            = false;  // RAS
bool TR_EnableSnapshotBlockOpts                         = false; 
bool TR_EnableParanoidRefCountChecks                    = false; 
bool TR_DisableThunkTupleJ2I                            = false; 
bool TR_TraceVIP                                        = false; 
bool TR_DisableRefinedBCDClobberEval                    = false; 
bool TR_DisableTLE                                      = false; 
bool TR_ForceVSSStackCompaction                         = false;  // always compact variable size symbols
bool TR_DisableVSSStackCompaction                       = false;  // never compact variable size symbols -- if not force or disable then use heuristic based on opt level and VSS total size
bool TR_EnableThisLiveRangeExtension                    = false;  // "this" live range extension
bool TR_EnableDowngradeOnHugeQSZ                        = false; 
bool TR_DisablePostProfileCompPriorityBoost             = false; 
bool TR_DisableBasicBlockPeepHole                       = false; 
bool TR_DisableMethodIsCold                             = false; 
bool TR_DisableNewStoreHint                             = false; 
bool TR_TraceScalarizeSSOps                             = false; 
bool TR_UseStrictStartupHints                           = false; 
bool TR_DisableOutlinedNew                              = false;  // Expand object allocation logic inline instead of using a fast jit helper
bool TR_TraceOpts                                       = false;  // list optimization group in its dynamic order
bool TR_DisableDecimalFormatPeephole                    = false;  //optimize DecimalFormat.format(BigDecimal.doubleValue())
bool TR_NoClassGC                                       = false;   // -Xnoclassgc
bool TR_Server                                          = false;   // -server
bool TR_EnableRATPurging                                = false;   // enable periodic RAT table purging
bool TR_UpgradeBootstrapAtWarm                          = false; 
bool TR_ForceLargeRAMoves                               = false;   // force 64 register moves in RA
bool TR_EnableLateCleanFolding                          = false;   // fold pdclean flags into pdstore nodes right before codegen
bool TR_PrivatizeOverlaps                               = false;   // avoid overlapping BCD stores
bool TR_DisableKnownObjectTable                         = false; 
bool TR_DisableAOTResolveDiffCLMethods                  = false;   // disable passing nested autos as parameters
bool TR_DisableMethodHandleInvokeOpts                   = false;   // JSR292
bool TR_InhibitRecompilation                            = false; 
bool TR_PaintDataCacheOnFree                            = false;   // Enable painting of data caches on reclamation
bool TR_DisableDataCacheReclamation                     = false;   // Disable reaping of data caches
bool TR_DisableUseDefForShadows                         = false; 
bool TR_DisableConservativeHotRecompilationForServerMode= false; 
bool TR_DisableRampupImprovements                       = false; 
bool TR_EnableCompilationSpreading                      = false; 
bool TR_LowerCountsForAotCold                           = false; 
bool TR_DisableBranchPreload                            = false; 
bool TR_EnableBranchPreload                             = false; 
bool TR_TerseRegisterPressureTrace                      = false; 
bool TR_DisableMutableCallSiteGuards                    = false;   // JSR292
bool TR_DisableCallConstUncommoning                     = false; 
bool TR_DisableWrtBarSrcObjCheck                        = false;  // enable srcobj range check for wrtBar
bool TR_DisableCodeCacheReclamation                     = false;  // Disable the freeing of compiled methods
bool TR_DisableClearCodeCacheFullFlag                   = false;  // Disable the re-enabling of the code cache when a method body is freed after the cache has become full
bool TR_EnableAOTRelocationTiming                       = false; 
bool TR_DisableBCDOppTracing                            = false; 
bool TR_DisableZonedToDFPReduction                      = false; 
bool TR_OldDataCacheImplementation                      = false; 
bool TR_EnableDataCacheStatistics                       = false; 
bool TR_DisableRedundantBCDSignElimination              = false; 
bool TR_AllowVPRangeNarrowingBasedOnDeclaredType        = false; 
bool TR_EnableScratchMemoryDebugging                    = false; 
bool TR_ProfileMemoryRegions                            = false; 
bool TR_DisableConverterReducer                         = false; 
bool TR_CompileTimeProfiler                             = false; 
bool TR_PerformLookaheadAtWarmCold                      = false; 
bool TR_ActivateCompThreadWhenHighPriReqIsBlocked       = false; 
bool TR_DisableIterativeSA                              = false; 
bool TR_TraceVPConstraints                              = false; 
bool TR_EnableMultipleGCRPeriods                        = false; 
bool TR_TraceKnownObjectGraph                           = false; 
bool TR_EnableAppThreadYield                            = false; 
bool TR_EnableRampupImprovements                        = false; 
bool TR_EnableGCRPatching                               = false; 
bool TR_DisableProfiledMethodInlining                   = false; 
bool TR_DisableSmartPlacementOfCodeCaches               = false; 
bool TR_DisableAESInHardware                            = false; 
bool TR_EnableMHCustomizationLogicCalls                 = false; 
bool TR_EnableJITHelpershashCodeImpl                    = false; 
bool TR_EnablePerfAsserts                               = false; 
bool TR_EnableAOTCacheReclamation                       = false; 
bool TR_DisableCPUUtilization                           = false; 
bool TR_TraceMethodIndex                                = false; 
bool TR_DisableGuardedCallArgumentRemat                 = false; 
bool TR_DisableMCSBypass                                = false;  // JSR292: MutableCallSite bypass optimization
bool TR_DisableHWProfilerThread                         = false; 
bool TR_DisableHWProfilerDataCollection                 = false; 
bool TR_RandomSeedSignatureHash                         = false; 
bool TR_DebugRedundantMonitorElimination                = false; 
bool TR_EnableScorchInterpBlockFrequencyProfiling       = false; 
bool TR_EnableSIMDLibrary                               = false; 
bool TR_EnableOSROnGuardFailure                         = false; 
bool TR_DisableOSR                                      = false; 
bool TR_DisableDualTLH                                  = false; 
bool TR_TraceUnsafeInlining                             = false; 
bool TR_DisableArrayStoreCheckOpts                      = false; 
bool TR_DisableFastAssumptionReclamation                = false; 
bool TR_UseHigherMethodCounts                           = false; 
bool TR_FullInlineUnderOSRDebug                         = false; 
bool TR_DisablePRBE                                     = false; 
bool TR_X86HLE                                          = false; 
bool TR_DisableAdaptiveDumbInliner                      = false; 
bool TR_EnableCopyingTROTInduction1Idioms               = false; 
bool TR_EnableLabelTargetNOPs                           = false; 
bool TR_TraceLabelTargetNOPs                            = false; 
bool TR_CrashDuringCompilation                          = false; 
bool TR_DisableShareableMethodHandleThunks              = false; 
bool TR_DisableCustomMethodHandleThunks                 = false; 
bool TR_DisableReducedPriorityForCustomMethodHandleThunks = false;
bool TR_TraceSA                                         = false; 
bool TR_EnablePrepareForOSREvenIfThatDoesNothing        = false; 
bool TR_EnableIprofilerChanges                          = false; 
bool TR_DumpPersistedIProfilerMethodNamesAndCounts      = false; 
bool TR_FirstRun                                        = false; 
bool TR_DumpInitialMethodNamesAndCounts                 = false; 
bool TR_DumpFinalMethodNamesAndCounts                   = false; 
bool TR_DisableRecognizedMethods                        = false; 
bool TR_DisableBitOpcode                                = false; 
bool TR_TraceTempUsage                                  = false; 
bool TR_TraceTempUsageMore                              = false;
bool TR_TracePREForOptimalSubNodeReplacement            = false; 
bool TR_EnableTrueRegisterModel                         = false; 
bool TR_PerfTool                                        = false; 
bool TR_DisableBranchOnCount                            = false; 
bool TR_LinkagePreserveStrategy2                        = false; 
bool TR_DisableLoopEntryAlignment                       = false; 
bool TR_EnableLoopEntryAlignment                        = false; 
bool TR_DisableLeafRoutineDetection                     = false; 
bool TR_EnableCompThreadThrottlingDuringStartup         = false; 
bool TR_EnableHardwareProfileRecompilation              = false;
bool TR_DisableSIMDArrayTranslate                       = false;
bool TR_DisableSIMDArrayCompare                         = false; 
bool TR_EnableJITHelpersoptimizedClone                  = false; 
bool TR_DontAllocateScratchBTL                          = false; 
bool TR_DisableZ13LoadImmediateOnCond                   = false; 
bool TR_TrustAllInterfaceTypeInfo                       = false; 
bool TR_DisableRefinedAliases                           = false; 
bool TR_DisableTM                                       = false; 
bool TR_DisableInlineCheckIfFinalizeObject              = false; 
bool TR_LexicalMemProfiler                              = false; 
bool TR_UseVmTotalCpuTimeAsAbstractTime                 = false; 
bool TR_HWProfilerDisableAOT                            = false; 
bool TR_HWProfilerDisableRIOverPrivateLinkage           = false; 
bool TR_DisableBCDArithChildOrdering                    = false; 
bool TR_EnableVirtualScratchMemory                      = false; 
bool TR_EnableVirtualPersistentMemory                   = false; 
bool TR_DisableArraysetStoreElimination                 = false; 
bool TR_DisableSeparateInitFromAlloc                    = false; 
bool TR_DisableMaxMinOptimization                       = false; 
bool TR_DisableUncountedUnrolls                         = false; 
bool TR_DisableUpgrades                                 = false; 
bool TR_EnableJitSamplingUpgradesDuringHWProfiling      = false; 
bool TR_DisableDeadStoreBailOut                         = false; 
bool TR_TraceReachability                               = false; 
bool TR_FloatMAF                                        = false; 
bool TR_ForceIEEEDivideByZeroException                  = false; 
bool TR_DisableDirectStaticAccessOnZ                    = false; 
bool TR_EnableRubyTieredCompilation                     = false; 
bool TR_EnableRIEMIT                                    = false; 
bool TR_DisableConservativeColdInlining                 = false; 
bool TR_DisableConservativeInlining                     = false; 
bool TR_EnableExpensiveOptsAtWarm                       = false; 
bool TR_DisableCheckcastAndProfiledGuardCoalescer       = false; 
bool TR_DisableArch11PackedToDFP                        = false; 
bool TR_DisableVectorRegGRA                             = false; 
bool TR_DisableSIMD                                     = false; 
bool TR_EnableRubyCodeCacheReclamation                  = false; 
bool TR_DisableSIMDStringCaseConv                       = false; 
bool TR_DisableSIMDUTF16BEEncoder                       = false; 
bool TR_DisableSIMDArrayCopy                            = false; 
bool TR_CheckStructureDuringExitExtraction              = false; 
bool TR_EnableRMODE64                                   = false; 
bool TR_EnableLocalVPSkipLowFreqBlock                   = false; 
bool TR_DisableLastITableCache                          = false; 
bool TR_StressTrampolines                               = false; 
bool TR_DisableSIMDUTF16LEEncoder                       = false; 
bool TR_DisableExitExtraction                           = false; 
bool TR_TraceExitExtraction                             = false; 
bool TR_VaryInlinerAggressivenessWithTime               = false; 
bool TR_EnableGRACostBenefitModel                       = false; 
bool TR_VerifyReferenceCounts                           = false; 
bool TR_DeferReferenceManipulations                     = false; 
bool TR_InlinerFanInUseCalculatedSize                   = false; 
bool TR_DisableProfilingDataReclamation                 = false; 
bool TR_DisableTrivialDeadBlockRemover                  = false; 
bool TR_DisableInvariantCodeMotion                      = false; 
bool TR_EnableSelfTuningScratchMemoryUsageBeforeCompile = false; 
bool TR_EnableSelfTuningScratchMemoryUsageInTrMemory    = false; 
bool TR_DisableUTF16BEEncoder                           = false; 
bool TR_DisableDAATrailingZero                          = false; 
bool TR_DisableDynamicRIBufferProcessing                = false; 
bool TR_DisableFastDLTOnLongRunningInterpreter          = false; 
bool TR_SubtractMethodCountsWhenIprofilerIsOff          = false; 
bool TR_SubtractLoopyMethodCounts                       = false; 
bool TR_UseOldIProfilerDeactivationLogic                = false; 
bool TR_EnableOutlinedNew                               = false; 
bool TR_DisableZealousCodegenOpts                       = false; 
bool TR_PrintAbsoluteTimestampInVerboseLog              = false; 
bool TR_InlineVeryLargeCompiledMethods                  = false; 
bool TR_HCRPatchClassPointers                           = false; 
bool TR_UseOldHCRGuardAOTRelocations                    = false; 
bool TR_TraceSEL                                        = false;  // Sign Extension Load
bool TR_DisableSupportForCpuSpentInCompilation          = false; 
bool TR_DisableSwitchAwayFromProfilingForHotAndVeryhot  = false; 
bool TR_UseHigherCountsForNonSCCMethods                 = false; 
bool TR_UseHigherMethodCountsAfterStartup               = false; 
bool TR_DisableNextGenHCR                               = false; 
bool TR_DisableMetadataReclamation                      = false; 
bool TR_DisableInlineIsInstance                         = false; 
bool TR_DisableSIMDStringHashCode                       = false; 
bool TR_IncreaseCountsForNonBootstrapMethods            = false; 
bool TR_ReduceCountsForMethodsCompiledDuringStartup     = false; 
bool TR_IncreaseCountsForMethodsCompiledOutsideStartup  = false; 
bool TR_EnableMethodTrampolineReservation               = false; 
bool TR_UseGlueIfMethodTrampolinesAreNotNeeded          = false; 
bool TR_EnableFpreductionAnnotation                     = false; 
bool TR_ExtractExitsByInvalidatingStructure             = false; 
bool TR_DisableCrackedEditOptimization                  = false; 
bool TR_InhibitRIBufferProcessingDuringDeepSteady       = false; 
bool TR_DontDowngradeWhenRIIsTemporarilyOff             = false; 
bool TR_DontRIUpgradeAOTWarmMethods                     = false; 
bool TR_UseRIOnlyForLargeQSZ                            = false; 
bool TR_EnableAggressiveLiveness                        = false; 
bool TR_DisableGuardedStaticFinalFieldFolding           = false; 
bool TR_DisableGLUColdRedirection                       = false; 
bool TR_DisableLocalCSEVolatileCommoning                = false; 
bool TR_TraceILWalks                                    = false; 
bool TR_DisableSIMDDoubleMaxMin                         = false; 
bool TR_DisableStoreOnCondition                         = false; 
bool TR_EnableTailCallOpt                               = false; 
bool TR_DisableInlineEXTarget                           = false; 
bool TR_EnableNewCheckCastInstanceOf                    = false; 
bool TR_DisableHardwareProfilerReducedWarm              = false; 
bool TR_RestrictStaticFieldFolding                      = false; 
bool TR_TraceILValidator                                = false; 
bool TR_EnableJProfilingInProfilingCompilations         = false; 
bool TR_EnableJProfiling                                = false; 
bool TR_DisableForcedEXInlining                         = false; 
bool TR_EnableOnsiteCacheForSuperClassTest              = false; 
bool TR_DisableVMCSProfiling                            = false; 
bool TR_EnableHardwareProfileIndirectDispatch           = false; 
bool TR_DisableCompareAndBranchInstruction              = false; 
bool TR_EnableMetadataBytecodePCToIAMap                 = false; 
bool TR_DisableHardwareProfilerReducedWarmUpgrades      = false; 
bool TR_DontAddHWPDataToIProfiler                       = false; 
bool TR_InlineNativeOnly                                = false; 
bool TR_DisableMultiTargetInlining                      = false; 
bool TR_DisableHardwareProfilerDuringStartup            = false; 
bool TR_RestrictInlinerDuringStartup                    = false; 
bool TR_EnableLoopVersionerCountAllocationFences        = false; 
bool TR_DisableHeapAllocOOL                             = false; 
bool TR_TraceMulDecomposition            = false; 
bool TR_EnableUnneededNarrowIntConversion = false; 
bool TR_TraceCGPreInstructionSelection  = false; 
bool TR_TraceCGPostInstructionSelection = false; 
bool TR_TraceCGPostRegisterAssignment   = false; 
bool TR_TraceCGPostBinaryEncoding       = false; 
bool TR_TraceCGMixedModeDisassembly     = false; 
bool TR_TraceCGBinaryCodedDecimal       = false; 
bool TR_TraceCGEvaluation               = false; 
bool TR_TraceEarlyStackMap              = false; 
bool TR_EnumerateBlock                   = false; 
bool TR_EnumerateInstruction             = false; 
bool TR_EnumerateNode                    = false; 
bool TR_EnumerateRegister                = false; 
bool TR_EnumerateSymbol                  = false; 
bool TR_EnumerateStructure               = false; 
bool TR_TraceRABasic                      = false; 
bool TR_TraceRADependencies               = false; 
bool TR_TraceRADetails                    = false; 
bool TR_TraceRAPreAssignmentInstruction   = false; 
bool TR_TraceRARegisterStates             = false; 
bool TR_TraceRASpillTemps                 = false; 
bool TR_TraceRAListing                    = false; 
bool TR_TraceGRABasic                     = false; 
bool TR_TraceGRAListing                   = false; //= TR_TraceRAListing;
bool TR_TraceLRAResults                   = false; 
bool TR_TraceRegisterITFBasic             = false; // = TR_TraceGRABasic;
bool TR_TraceRegisterITFBuild             = false; 
bool TR_TraceRegisterITFColour            = false;


}; /* Class CompilerOptions */

} /* namespace TR */

#endif  /* OMR_COMPILER_OPTIONS_HPP */